export const USER = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  UNSET_CURRENT_USER: 'UNSET_CURRENT_USER',
  TOGGLE_AUTH_IN_PROGRESS: 'TOGGLE_AUTH_IN_PROGRESS'
};

export const ERROR = {
	SET_ERROR: 'SET_ERROR',
	UNSET_ERROR: 'UNSET_ERROR'
};